name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: Dylan

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Especifica la versión de Python que necesitas

      - name: Install dependencies
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run server
        run: geotaxi.py  

        
