name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Usa tu propio runner

    steps:
      # Paso 1: Checkout del código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Copiar los archivos al directorio de la aplicación en la instancia
      - name: Move code to application directory
        run: |
          cp -R . ~/actions-runner/_work/Geotaxi/Geotaxi/

      # Paso 3: Instalar dependencias de Python (si es necesario)
      - name: Install dependencies
        run: |
          cd ~/actions-runner/_work/Geotaxi/Geotaxi
          pip install -r requirements.txt  # Instala dependencias si es necesario

      # Paso 4: Ejecutar el script Python
      - name: Run Python script
        run: |
          cd ~/actions-runner/_work/Geotaxi/Geotaxi
          python geotaxi.py  # Reemplaza 'main.py' con el nombre de tu script Python

      # Paso 5: Verificar que el archivo index.html esté en la ubicación correcta
      - name: Verify index.html
        run: |
          cd ~/actions-runner/_work/Geotaxi/Geotaxi
          ls -la  # Lista los archivos para confirmar que index.html está allí
