name: Test Runner

on:
  push:
    branches:
      - FELIX

jobs:
  deploy:
    runs-on: self-hosted  # Usa tu propio runner

    steps:
      # Paso 1: Checkout del código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Crear un nuevo directorio para evitar conflictos
      - name: Create application directory
        run: mkdir -p /home/ubuntu/actions-runner/_work/Geotaxi/Geotaxi/Geotaxi_new

      # Paso 3: Copiar los archivos al nuevo directorio de la aplicación en la instancia excluyendo el directorio de destino
      - name: Move code to application directory excluding destination directory
        run: |
          rsync -av --progress --exclude='Geotaxi_new' * /home/ubuntu/actions-runner/_work/Geotaxi/Geotaxi/Geotaxi_new/
          echo "Copied files to Geotaxi_new directory"

      # Paso 4: Listar archivos para asegurar que 'index.html' esté en su lugar
      - name: List files in Geotaxi_new
        run: |
          ls -la /home/ubuntu/actions-runner/_work/Geotaxi/Geotaxi/Geotaxi_new/
          echo "Listed files in Geotaxi_new directory"

      # Paso 5: Reiniciar Nginx para asegurar que los cambios se reflejan
      - name: Restart web server
        run: |
          sudo systemctl reload nginx  # Recarga la configuración de Nginx para aplicar cambios
          echo "Reloaded Nginx"

      # Paso 6: Verificar que el archivo 'index.html' esté en la ubicación correcta en el servidor web
      - name: Verify deployed index.html
        run: |
          if [ -f /home/ubuntu/actions-runner/_work/Geotaxi/Geotaxi/Geotaxi_new/index.html ]; then 
            echo "Deployed index.html found. Verification successful.";
          else 
            echo "Deployed index.html not found. Verification failed."; 
            exit 1; 
          fi
