name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Usa tu propio runner

    steps:
      # Paso 1: Checkout del código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Crear un nuevo directorio para evitar conflicto
      - name: Create application directory
        run: mkdir -p ~/actions-runner/_work/Geotaxi/Geotaxi_new

      # Paso 3: Copiar los archivos al nuevo directorio de la aplicación en la instancia
      - name: Move code to application directory
        run: |
          cp -R * ~/actions-runner/_work/Geotaxi/Geotaxi_new/

      # Paso 4: Crear un entorno virtual
      - name: Set up Python virtual environment
        run: |
          python3 -m venv ~/actions-runner/_work/Geotaxi/Geotaxi_new/venv
          source ~/actions-runner/_work/Geotaxi/Geotaxi_new/venv/bin/activate

      # Paso 5: Instalar dependencias de Python en el entorno virtual
      - name: Install dependencies
        run: |
          source ~/actions-runner/_work/Geotaxi/venv/bin/activate
          pip install --upgrade pip  # Asegurarse de tener la última versión de pip
          pip install -r ~/actions-runner/_work/Geotaxi/requirements.txt  # Instala dependencias

      # Paso 6: Ejecutar el script Python usando el entorno virtual
      - name: Run Python script
        run: |
          source ~/actions-runner/_work/Geotaxi/Geotaxi_new/venv/bin/activate
          python ~/actions-runner/_work/Geotaxi/Geotaxi_new/geotaxi.py  # Reemplaza 'geotaxi.py' con el nombre de tu script Python

      # Paso 7: Verificar que el archivo index.html esté en la ubicación correcta
      - name: Verify index.html
        run: |
          cd ~/actions-runner/_work/Geotaxi/Geotaxi_new
          ls -la  # Lista los archivos para confirmar que index.html está allí

