name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Usa tu propio runner

    steps:
      # Paso 1: Checkout del código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Crear un nuevo directorio para evitar conflictos
      - name: Create application directory
        run: mkdir -p ~/actions-runner/_work/Geotaxi/Geotaxi_new

      # Paso 3: Copiar los archivos al nuevo directorio de la aplicación en la instancia
      - name: Move code to application directory
        run: |
          cp -R * ~/actions-runner/_work/Geotaxi/Geotaxi_new/
          echo "Copied files to Geotaxi_new directory"
      
      # Paso 4: Listar archivos para asegurar que 'index.html' esté en su lugar
      - name: List files in Geotaxi_new
        run: |
          ls -la ~/actions-runner/_work/Geotaxi/Geotaxi_new/
          echo "Listed files in Geotaxi_new directory"

      # Paso 5: Verificar que el archivo 'index.html' esté en la ubicación correcta
      - name: Verify index.html
        run: |
          if [ -f ~/actions-runner/_work/Geotaxi/Geotaxi_new/index.html ]; then 
            echo "index.html found. Verification successful.";
          else 
            echo "index.html not found. Verification failed."; 
            exit 1; 
          fi
